# config/tickers.py
# ─────────────────────────────────────────────────────────────────
# Per-ticker configuration. Add/remove tickers here only.
# Each entry is fully independent — own thresholds, cooldown,
# and Google Sheets tab.
#
# To list all available xyz assets run:
# python3 -c "
# from core.hl_client import fetch_meta_and_asset_ctxs
# data = fetch_meta_and_asset_ctxs()
# print([a['name'] for a in data[0]['universe']])
# "
# ─────────────────────────────────────────────────────────────────

TICKERS = {
    "NVDA": {
        "hl_asset": "xyz:NVDA",
        "full_name": "Nvidia",
        "price_change_threshold_pct": 2.0,
        "price_window_minutes": 5,
        "volume_change_threshold_pct": 15.0,
        "volume_window_minutes": 180,
        "volume_reset_drop_pct": 30.0,
        "oi_window_hours": 3,
        "enable_volume_trigger": True,
        "alert_cooldown_seconds": 300,
        "sheets_tab": "NVDA",
    },
    "TSLA": {
        "hl_asset": "xyz:TSLA",
        "full_name": "Tesla",
        "price_change_threshold_pct": 3.0,
        "price_window_minutes": 5,
        "volume_change_threshold_pct": 20.0,
        "volume_window_minutes": 180,
        "volume_reset_drop_pct": 30.0,
        "oi_window_hours": 3,
        "enable_volume_trigger": True,
        "alert_cooldown_seconds": 300,
        "sheets_tab": "TSLA",
    },
    "AAPL": {
        "hl_asset": "xyz:AAPL",
        "full_name": "Apple",
        "price_change_threshold_pct": 2.0,
        "price_window_minutes": 5,
        "volume_change_threshold_pct": 15.0,
        "volume_window_minutes": 180,
        "volume_reset_drop_pct": 30.0,
        "oi_window_hours": 3,
        "enable_volume_trigger": True,
        "alert_cooldown_seconds": 300,
        "sheets_tab": "AAPL",
    },
    "MSFT": {
        "hl_asset": "xyz:MSFT",
        "full_name": "Microsoft",
        "price_change_threshold_pct": 2.0,
        "price_window_minutes": 5,
        "volume_change_threshold_pct": 15.0,
        "volume_window_minutes": 180,
        "volume_reset_drop_pct": 30.0,
        "oi_window_hours": 3,
        "enable_volume_trigger": True,
        "alert_cooldown_seconds": 300,
        "sheets_tab": "MSFT",
    },
    "GOOGL": {
        "hl_asset": "xyz:GOOGL",
        "full_name": "Google Alphabet",
        "price_change_threshold_pct": 2.0,
        "price_window_minutes": 5,
        "volume_change_threshold_pct": 15.0,
        "volume_window_minutes": 180,
        "volume_reset_drop_pct": 30.0,
        "oi_window_hours": 3,
        "enable_volume_trigger": True,
        "alert_cooldown_seconds": 300,
        "sheets_tab": "GOOGL",
    },
    "META": {
        "hl_asset": "xyz:META",
        "full_name": "Meta",
        "price_change_threshold_pct": 2.5,
        "price_window_minutes": 5,
        "volume_change_threshold_pct": 20.0,
        "volume_window_minutes": 180,
        "volume_reset_drop_pct": 30.0,
        "oi_window_hours": 3,
        "enable_volume_trigger": True,
        "alert_cooldown_seconds": 300,
        "sheets_tab": "META",
    },
    "AMZN": {
        "hl_asset": "xyz:AMZN",
        "full_name": "Amazon",
        "price_change_threshold_pct": 2.5,
        "price_window_minutes": 5,
        "volume_change_threshold_pct": 20.0,
        "volume_window_minutes": 180,
        "volume_reset_drop_pct": 30.0,
        "oi_window_hours": 3,
        "enable_volume_trigger": True,
        "alert_cooldown_seconds": 300,
        "sheets_tab": "AMZN",
    },
    "GOLD": {
        "hl_asset": "xyz:GOLD",
        "full_name": "Gold",
        "price_change_threshold_pct": 1.0,
        "price_window_minutes": 5,
        "volume_change_threshold_pct": 25.0,
        "volume_window_minutes": 180,
        "volume_reset_drop_pct": 30.0,
        "oi_window_hours": 3,
        "enable_volume_trigger": True,
        "alert_cooldown_seconds": 300,
        "sheets_tab": "GOLD",
    },
    "SP500": {
        "hl_asset": "xyz:SP500",
        "full_name": "S&P 500",
        "price_change_threshold_pct": 1.0,
        "price_window_minutes": 5,
        "volume_change_threshold_pct": 20.0,
        "volume_window_minutes": 180,
        "volume_reset_drop_pct": 30.0,
        "oi_window_hours": 3,
        "enable_volume_trigger": True,
        "alert_cooldown_seconds": 300,
        "sheets_tab": "SP500",
    },
    "PLTR": {
        "hl_asset": "xyz:PLTR",
        "full_name": "Palantir",
        "price_change_threshold_pct": 3.0,
        "price_window_minutes": 5,
        "volume_change_threshold_pct": 20.0,
        "volume_window_minutes": 180,
        "volume_reset_drop_pct": 30.0,
        "oi_window_hours": 3,
        "enable_volume_trigger": True,
        "alert_cooldown_seconds": 300,
        "sheets_tab": "PLTR",
    },
    "AMD": {
        "hl_asset": "xyz:AMD",
        "full_name": "AMD",
        "price_change_threshold_pct": 3.0,
        "price_window_minutes": 5,
        "volume_change_threshold_pct": 20.0,
        "volume_window_minutes": 180,
        "volume_reset_drop_pct": 30.0,
        "oi_window_hours": 3,
        "enable_volume_trigger": True,
        "alert_cooldown_seconds": 300,
        "sheets_tab": "AMD",
    },
    "MSTR": {
        "hl_asset": "xyz:MSTR",
        "full_name": "MicroStrategy",
        "price_change_threshold_pct": 4.0,
        "price_window_minutes": 5,
        "volume_change_threshold_pct": 25.0,
        "volume_window_minutes": 180,
        "volume_reset_drop_pct": 30.0,
        "oi_window_hours": 3,
        "enable_volume_trigger": True,
        "alert_cooldown_seconds": 300,
        "sheets_tab": "MSTR",
    },
    "COIN": {
        "hl_asset": "xyz:COIN",
        "full_name": "Coinbase",
        "price_change_threshold_pct": 3.5,
        "price_window_minutes": 5,
        "volume_change_threshold_pct": 25.0,
        "volume_window_minutes": 180,
        "volume_reset_drop_pct": 30.0,
        "oi_window_hours": 3,
        "enable_volume_trigger": True,
        "alert_cooldown_seconds": 300,
        "sheets_tab": "COIN",
    },
    "HOOD": {
        "hl_asset": "xyz:HOOD",
        "full_name": "Robinhood",
        "price_change_threshold_pct": 3.5,
        "price_window_minutes": 5,
        "volume_change_threshold_pct": 25.0,
        "volume_window_minutes": 180,
        "volume_reset_drop_pct": 30.0,
        "oi_window_hours": 3,
        "enable_volume_trigger": True,
        "alert_cooldown_seconds": 300,
        "sheets_tab": "HOOD",
    },
    "INTC": {
        "hl_asset": "xyz:INTC",
        "full_name": "Intel",
        "price_change_threshold_pct": 3.0,
        "price_window_minutes": 5,
        "volume_change_threshold_pct": 20.0,
        "volume_window_minutes": 180,
        "volume_reset_drop_pct": 30.0,
        "oi_window_hours": 3,
        "enable_volume_trigger": True,
        "alert_cooldown_seconds": 300,
        "sheets_tab": "INTC",
    },
}
